import Background from "@/components/background";
import { Header } from "@/components/header";
import Providers from "@/components/providers";
import { Toaster } from "@rapidlaunch/ui/sonner";
import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${GeistSans.className}`}>
                <Providers>
                    <Background>
                        <Header />
                        {children}
                        <Toaster position="top-center" />
                    </Background>
                </Providers>
            </body>
        </html>
    );
}
